//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EF_TransactionScope.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBooking
    {
        public int FlightId { get; set; }
        public string FilghtName { get; set; }
        public string Number { get; set; }
        public System.DateTime TravellingDate { get; set; }
    }
}
